/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IHegicOperationalTreasuryInterface extends ethers.utils.Interface {
  functions: {
    "lockedLiquidity(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "lockedLiquidity",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "lockedLiquidity",
    data: BytesLike
  ): Result;

  events: {};
}

export class IHegicOperationalTreasury extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IHegicOperationalTreasuryInterface;

  functions: {
    lockedLiquidity(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      state: number;
      strategy: string;
      negativepnl: BigNumber;
      positivepnl: BigNumber;
      expiration: number;
      0: number;
      1: string;
      2: BigNumber;
      3: BigNumber;
      4: number;
    }>;

    "lockedLiquidity(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      state: number;
      strategy: string;
      negativepnl: BigNumber;
      positivepnl: BigNumber;
      expiration: number;
      0: number;
      1: string;
      2: BigNumber;
      3: BigNumber;
      4: number;
    }>;
  };

  lockedLiquidity(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    state: number;
    strategy: string;
    negativepnl: BigNumber;
    positivepnl: BigNumber;
    expiration: number;
    0: number;
    1: string;
    2: BigNumber;
    3: BigNumber;
    4: number;
  }>;

  "lockedLiquidity(uint256)"(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    state: number;
    strategy: string;
    negativepnl: BigNumber;
    positivepnl: BigNumber;
    expiration: number;
    0: number;
    1: string;
    2: BigNumber;
    3: BigNumber;
    4: number;
  }>;

  callStatic: {
    lockedLiquidity(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      state: number;
      strategy: string;
      negativepnl: BigNumber;
      positivepnl: BigNumber;
      expiration: number;
      0: number;
      1: string;
      2: BigNumber;
      3: BigNumber;
      4: number;
    }>;

    "lockedLiquidity(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      state: number;
      strategy: string;
      negativepnl: BigNumber;
      positivepnl: BigNumber;
      expiration: number;
      0: number;
      1: string;
      2: BigNumber;
      3: BigNumber;
      4: number;
    }>;
  };

  filters: {};

  estimateGas: {
    lockedLiquidity(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "lockedLiquidity(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    lockedLiquidity(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "lockedLiquidity(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
